import { createContext, useContext, useState, useEffect } from 'react';
import { NativeModules, Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

function detectSystemLang() {
  try {
    let locale = '';
    if (Platform.OS === 'ios') {
      locale =
        NativeModules.SettingsManager?.settings?.AppleLocale ||
        NativeModules.SettingsManager?.settings?.AppleLanguages?.[0] || '';
    } else if (Platform.OS === 'android') {
      locale = NativeModules.I18nManager?.localeIdentifier || '';
    }
    if (!locale && typeof Intl !== 'undefined') {
      locale = Intl.DateTimeFormat().resolvedOptions().locale || '';
    }
    return locale.toLowerCase().startsWith('tr') ? 'tr' : 'en';
  } catch {
    return 'en';
  }
}

const translations = {
  en: {
    appName: 'Birik',
    appSubtitle: 'Keep tabs on your income and expenses',
    createdBy: 'Created by',
    signOut: 'Sign out',
    navOverview: 'Overview',
    navTransactions: 'Transactions',
    navAnalytics: 'Analytics',
    navBudgets: 'Budgets',
    navGoals: 'Goals',
    navSubscriptions: 'Subscriptions',
    navProfile: 'Profile',
    usernameRequired: 'Username cannot be empty',
    dangerZone: 'Danger Zone',
    deleteAccountBtn: 'Delete Account',
    deleteAccountWarning: 'This permanently deletes your account along with all transactions, budgets, and subscriptions. This cannot be undone.',
    deleteAccountTypeLabel: 'Type DELETE to confirm',
    deleteAccountTypeWrong: 'Please type DELETE to confirm',
    deleteAccountNeedPassword: 'Password required',
    deleteAccountConfirmBtn: 'Delete forever',
    deletingAccount: 'Deleting…',
    deleteAccountFailed: 'Failed to delete account',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    registerAgreeTerms: 'I agree to the',
    registerAgreePrefix: 'I have read and agree to the',
    registerAgreeAccept: '',
    registerAnd: 'and',
    signInTitle: 'Sign in to your account',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    passwordPlaceholder: 'Min. 8 characters',
    signingIn: 'Signing in…',
    signInBtn: 'Sign in',
    noAccount: "Don't have an account?",
    registerLink: 'Register',
    createAccountTitle: 'Create an account',
    creatingAccount: 'Creating account…',
    createAccountBtn: 'Create account',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 8 characters',
    passwordNeedsUpper: 'Password must contain at least one uppercase letter',
    passwordNeedsNumber: 'Password must contain at least one number',
    pwRuleLength: 'At least 8 characters',
    pwRuleUpper: 'One uppercase letter',
    pwRuleNumber: 'One number',
    pwStrengthWeak: 'Weak',
    pwStrengthFair: 'Fair',
    pwStrengthStrong: 'Strong',
    serverError: 'Could not connect to server',
    loginInvalidCredentials: 'Email or password is incorrect.',
    checkYourEmail: 'Check your email',
    verificationSent: 'We sent a verification link to',
    spamWarning: "Can't find the email? Check your spam folder.",
    backToSignIn: 'Back to sign in',
    verifyMethodEmail: 'Email',
    verifyMethodSms: 'SMS',
    phoneNumber: 'Phone Number',
    phonePlaceholder: '+1 234 567 8900',
    sendCode: 'Send Code',
    sendingCode: 'Sending…',
    otpCode: 'Verification Code',
    otpPlaceholder: '6-digit code',
    verifyAndCreate: 'Verify & Create Account',
    verifyingCode: 'Verifying…',
    smsSent: 'We sent a 6-digit code to',
    invalidOtp: 'Invalid code. Please try again.',
    accountCreated: 'Account created! You can now sign in.',
    backToLanding: 'Back to home',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Reset your password',
    forgotPasswordDesc: "Enter your email and we'll send you a reset link.",
    sendResetLink: 'Send reset link',
    sendingResetLink: 'Sending…',
    resetEmailSent: 'Reset link sent! Check your inbox.',
    income: 'Income',
    expenses: 'Expenses',
    balance: 'Balance',
    addTransaction: 'Add Transaction',
    description: 'Description',
    descriptionPlaceholder: 'Description',
    amount: 'Amount',
    amountPlaceholder: 'Amount',
    incomeOption: 'Income',
    expenseOption: 'Expense',
    type: 'Type',
    addBtn: 'Add',
    transactions: 'Transactions',
    allTypes: 'All Types',
    allCategories: 'All Categories',
    date: 'Date',
    category: 'Category',
    noTransactions: 'No transactions found',
    searchPlaceholder: 'Search description…',
    dateFrom: 'From',
    dateTo: 'To',
    clearFilters: 'Clear',
    sortBy: 'Sort',
    sortDateDesc: 'Newest first',
    sortDateAsc: 'Oldest first',
    sortAmountDesc: 'Amount: high → low',
    sortAmountAsc: 'Amount: low → high',
    deleteTransaction: 'Delete Transaction',
    deleteConfirmLine1: 'Are you sure you want to delete',
    cancelBtn: 'Cancel',
    deleteBtn: 'Delete',
    food: 'Food',
    housing: 'Housing',
    utilities: 'Utilities',
    transport: 'Transport',
    entertainment: 'Entertainment',
    salary: 'Salary',
    freelance: 'Freelance',
    investment: 'Investment',
    rental: 'Rental Income',
    bonus: 'Bonus',
    other: 'Other',
    dailyDist: 'Daily Balance',
    dailyDistDay: 'Day',
    expenseBreakdown: 'Expense Breakdown',
    recentActivity: 'Recent Activity',
    noTransactionsDash: 'No transactions yet',
    addFirstTransaction: 'Add your first income or expense to see insights.',
    statAvgDaily: 'Avg Daily Spend',
    statDaysElapsed: 'days elapsed',
    statDaysLeft: 'Days Left',
    statOfMonth: 'of',
    statTopCat: 'Top Category',
    statLargestExp: 'Largest Expense',
    statSavingsRate: 'Savings Rate',
    statAllTime: 'All time',
    statVsLastMonth: 'vs Last Month',
    statSpending: 'spending',
    statThisMonth: 'This Month',
    statTransactions: 'transactions',
    statTransaction: 'transaction',
    statTxCount: 'tx',
    dailyDistTapHint: 'Tap a bar to see details',
    dailyDistEmpty: 'No activity for that day',
    dailyDistNet: 'Net',
    projTitle: 'End-of-month projection',
    projSubtitle: 'based on typical daily spending + known upcoming charges',
    projSpentSoFar: 'spent so far',
    projDaysLeft: 'days left',
    projVsLast: 'vs last month',
    projScheduled: 'scheduled',
    runningBalance: 'Balance',
    totalBudget: 'Total Budget',
    totalGoals: 'Total Goals',
    totalSaved: 'Total Saved',
    goalsSummary: 'Savings Goals',
    noTransactionsAnalytics: 'Add transactions to see analytics',
    avgExpense: 'Avg Expense',
    busiestDay: 'Busiest Day',
    biggestExpense: 'Biggest Expense',
    last30Days: 'Last 30 Days',
    byCategory: 'By Category',
    spendingTrends: 'Spending Trends',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    vsLastMonth: 'vs last month',
    topMovers: 'Top Category Changes',
    catAddNew: 'New category',
    catAddPlaceholder: 'Category name…',
    catAddErr_empty: 'Please enter a name.',
    catAddErr_reserved: 'That name is reserved.',
    catAddErr_exists: 'Category already exists.',
    budgets: 'Budgets',
    budgetEmpty: 'No budgets yet. Set monthly limits to track your spending.',
    budgetAdd: 'Set Budget',
    budgetEdit: 'Edit Budget',
    budgetMonthlyLimit: 'Monthly Limit',
    budgetSpent: 'Spent',
    budgetRemaining: 'Remaining',
    budgetOverBy: 'Over by',
    budgetOnTrack: 'On track',
    budgetWarning: 'Close to limit',
    budgetExceeded: 'Over budget',
    budgetSelectCategory: 'Category',
    toastTxAdded: 'Transaction added',
    toastTxDeleted: 'Transaction deleted',
    toastTxUpdated: 'Transaction updated',
    toastGoalSaved: 'Goal saved',
    toastGoalDeleted: 'Goal deleted',
    toastBudgetSaved: 'Budget saved',
    toastBudgetDeleted: 'Budget removed',
    toastSubAdded: 'Subscription added',
    toastSubUpdated: 'Subscription updated',
    toastSubDeleted: 'Subscription deleted',
    permissionDenied: 'Permission denied',
    subAllCategories: 'All Categories',
    subFilterByCat: 'Filter by category',
    subscriptions: 'Subscriptions',
    subMonthlyTotal: 'Monthly Total',
    subActive: 'active',
    subEmpty: 'No subscriptions yet. Tap + to add one.',
    subAdd: 'Add Subscription',
    subEdit: 'Edit',
    subName: 'Service Name',
    subBillingCycle: 'Billing Cycle',
    subStartedAt: 'Started',
    subNextBilling: 'Next Billing',
    subNotes: 'Notes',
    subNotesPlaceholder: 'Optional notes',
    subToday: 'Today',
    subOverdue: 'Overdue',
    subDays: 'days',
    subMonthsActive: 'Months Active',
    subWeeksActive: 'Weeks Active',
    subYearsActive: 'Years Active',
    subTotalSpent: 'Total Spent',
    subAutoCharge: 'Auto-charge as expense',
    subAutoChargeDesc: 'When on, each billing date is automatically logged as an expense.',
    subAutoChargeBadge: 'Auto',
    subDeleteTitle: 'Delete Subscription',
    subCycle_weekly: 'Weekly',
    subCycle_monthly: 'Monthly',
    subCycle_yearly: 'Yearly',
    subCat_ai: 'AI',
    subCat_entertainment: 'Entertainment',
    subCat_music: 'Music',
    subCat_finance: 'Finance',
    subCat_productivity: 'Productivity',
    subCat_health: 'Health',
    subCat_news: 'News',
    subCat_telecom: 'Telecom',
    subCat_other: 'Other',
    dashGoals: 'Savings Goals',
    dashGoalsSeeAll: 'See all',
    goalAdd: 'Add Goal',
    goalEdit: 'Edit Goal',
    goalEmoji: 'Icon',
    goalName: 'Goal Name',
    goalNamePlaceholder: 'Vacation, new laptop…',
    goalTarget: 'Target',
    goalSaved: 'Saved so far',
    goalTargetDate: 'Target date',
    goalOptional: 'optional',
    goalEmpty: 'No goals yet. Tap + to add one.',
    goalDeleteTitle: 'Delete Goal',
    goalComplete: 'Goal reached!',
    goalRemaining: 'to go',
    goalDaysLeft: 'days left',
    goalToday: 'Due today',
    goalOverdue: 'Overdue',
    subReminder: 'Email Reminder',
    subReminderNone: 'No reminder',
    subReminder3: '3 days before',
    subReminder7: '7 days before',
    subReminder14: '14 days before',
    profileTitle: 'Profile',
    displayName: 'Display Name',
    displayNamePlaceholder: 'Your name',
    currencyLabel: 'Currency',
    saveBtn: 'Save',
    savingBtn: 'Saving…',
    linkedAccounts: 'Linked Accounts',
    linkedEmail: 'Email',
    linkedPhone: 'Phone',
    notLinked: 'Not linked',
    landingTagline: 'Free · No credit card needed',
    landingHeadline1: 'Build your',
    landingHeadline2: 'savings.',
    landingSubtitle: 'Log income and expenses, track subscriptions, and import bank statements with AI. Build your savings, brick by brick.',
    landingGetStarted: 'Create free account',
    landingSignIn: 'Sign in',
    landingFeature1Title: 'Add a transaction in seconds',
    landingFeature1Desc: "Type a description, enter the amount, pick a category. That's it. No setup, no forms, no friction.",
    landingFeature2Title: 'See your spending at a glance',
    landingFeature2Desc: 'Your dashboard shows your balance, recent activity, and a 30-day breakdown the moment you open the app.',
    landingFeature3Title: 'Works in your currency',
    landingFeature3Desc: 'Choose from USD, EUR, GBP, TRY, JPY, and more. Your currency preference sticks across every screen.',
    landingFeature4Title: 'Upload anything — AI reads it',
    landingFeature4Desc: "Drop a bank statement PDF or snap a photo. AI extracts every transaction automatically, so you don't have to type a thing.",
    landingFeature5Title: 'Never lose track of subscriptions',
    landingFeature5Desc: "Track every recurring service in one place. Set email reminders before billing dates so you're never caught off guard.",
    landingFeature6Title: 'Set savings goals',
    landingFeature6Desc: 'Create goals for anything — a trip, a laptop, an emergency fund. Watch the progress bar fill up as you save.',
    landingCtaTitle: 'Start tracking today.',
    landingCtaSub: 'Free forever · No credit card',
    editBtn: 'Edit',
    preferencesTitle: 'Preferences',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    themeSystem: 'System',
    langSystem: 'System',
    language: 'Language',
    theme: 'Theme',
    showAdvanced: 'Advanced',
    hideAdvanced: 'Hide advanced',
    toastProfileSaved: 'Profile saved',
    biometricLock: 'Face ID / Fingerprint Lock',
    bioUnlockBtn: 'Unlock with Face ID / Fingerprint',
    bioUsePassword: 'Sign in with password instead',
    offlineMode: 'No internet connection',
    offlinePending: 'pending',
    offlineSyncing: 'Syncing',
    recTitle: 'Recurring',
    recEmpty: 'No recurring rules yet. Tap + to add one.',
    recAdd: 'Add Recurring Rule',
    recEdit: 'Edit Recurring Rule',
    recSaved: 'Rule saved',
    recDeleted: 'Rule deleted',
    recFrequency: 'Frequency',
    rec_weekly: 'Weekly',
    rec_monthly: 'Monthly',
    rec_yearly: 'Yearly',
    recDayOfMonth: 'Day of Month',
    recStartDate: 'Start Date',
    recEndDate: 'End Date',
    recDeleteTitle: 'Delete Rule',
    recPaused: 'Paused',
    recActive: 'Active',
    recNextRun: 'Next',
    navRecurring: 'Recurring',
    subStatusActive: 'Active',
    subStatusInactive: 'Inactive',
    subAddAsExpense: 'Add as Expense',
    subExpenseAdded: 'Added!',
    importTitle: 'Import Statement',
    importDesc: 'Take a photo or upload a PDF of your bank/credit card statement. AI will extract transactions automatically.',
    importAnalyzing: 'Analyzing statement…',
    importCamera: 'Take a Photo',
    importCameraDesc: 'Photograph your bank statement',
    importGallery: 'Choose from Gallery',
    importGalleryDesc: 'Pick an existing image',
    importPDF: 'Upload PDF',
    importPDFDesc: 'Select a PDF bank statement',
    importPreviewCount: 'transactions found. Review and edit categories before importing.',
    importConfirm: 'Import',
    importSuccess: 'transactions imported',
    importNoTxFound: 'No transactions found. Make sure the file is a clear bank statement.',
    monthlyOverview: 'Monthly Overview',
    insightHowGoing: 'How is this month going?',
    insightSameDayLastMonth: 'same day last month',
    insightOnTrack: 'Under last month',
    insightOverSpending: 'Over last month',
    dashCustomize: 'Customize Dashboard',
    dashSectionStats: 'Stats Cards',
    dashSectionBreakdown: 'Expense Breakdown',
    dashSectionDaily: 'Daily Balance',
    dashSectionProjection: 'Month Projection',
    dashSectionRecent: 'Recent Activity',
    dashSectionGoals: 'Savings Goals',
  },
  tr: {
    appName: 'Birik',
    appSubtitle: 'Gelir ve giderlerinizi takip edin',
    createdBy: 'Geliştiren',
    signOut: 'Çıkış yap',
    navOverview: 'Özet',
    navTransactions: 'İşlemler',
    navAnalytics: 'Analiz',
    navBudgets: 'Bütçeler',
    navGoals: 'Hedefler',
    navSubscriptions: 'Abonelikler',
    navProfile: 'Profil',
    usernameRequired: 'Kullanıcı adı boş olamaz',
    dangerZone: 'Tehlikeli Bölge',
    deleteAccountBtn: 'Hesabı Sil',
    deleteAccountWarning: 'Bu işlem hesabınızı kalıcı olarak siler. Geri alınamaz.',
    deleteAccountTypeLabel: 'Onaylamak için DELETE yazın',
    deleteAccountTypeWrong: 'Lütfen DELETE yazın',
    deleteAccountNeedPassword: 'Şifre gerekli',
    deleteAccountConfirmBtn: 'Kalıcı olarak sil',
    deletingAccount: 'Siliniyor…',
    deleteAccountFailed: 'Hesap silinemedi',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfService: 'Kullanım Koşulları',
    registerAgreeTerms: 'Okudum ve kabul ediyorum:',
    registerAgreePrefix: '',
    registerAgreeAccept: 'okudum ve kabul ediyorum.',
    registerAnd: 've',
    signInTitle: 'Hesabınıza giriş yapın',
    email: 'E-posta',
    emailPlaceholder: 'siz@ornek.com',
    password: 'Şifre',
    confirmPassword: 'Şifreyi Onayla',
    passwordPlaceholder: 'En az 8 karakter',
    signingIn: 'Giriş yapılıyor…',
    signInBtn: 'Giriş yap',
    noAccount: 'Hesabınız yok mu?',
    registerLink: 'Kayıt ol',
    createAccountTitle: 'Hesap oluştur',
    creatingAccount: 'Hesap oluşturuluyor…',
    createAccountBtn: 'Hesap oluştur',
    alreadyHaveAccount: 'Zaten hesabınız var mı?',
    signInLink: 'Giriş yap',
    passwordMismatch: 'Şifreler eşleşmiyor',
    passwordTooShort: 'Şifre en az 8 karakter olmalı',
    passwordNeedsUpper: 'Şifre en az bir büyük harf içermeli',
    passwordNeedsNumber: 'Şifre en az bir rakam içermeli',
    pwRuleLength: 'En az 8 karakter',
    pwRuleUpper: 'Bir büyük harf',
    pwRuleNumber: 'Bir rakam',
    pwStrengthWeak: 'Zayıf',
    pwStrengthFair: 'Orta',
    pwStrengthStrong: 'Güçlü',
    serverError: 'Sunucuya bağlanılamadı',
    loginInvalidCredentials: 'E-posta veya şifre hatalı.',
    checkYourEmail: 'E-postanızı kontrol edin',
    verificationSent: 'Doğrulama bağlantısı gönderildi:',
    spamWarning: 'E-postayı bulamıyor musunuz? Spam klasörünü kontrol edin.',
    backToSignIn: 'Girişe dön',
    verifyMethodEmail: 'E-posta',
    verifyMethodSms: 'SMS',
    phoneNumber: 'Telefon Numarası',
    phonePlaceholder: '+90 555 123 4567',
    sendCode: 'Kod Gönder',
    sendingCode: 'Gönderiliyor…',
    otpCode: 'Doğrulama Kodu',
    otpPlaceholder: '6 haneli kod',
    verifyAndCreate: 'Doğrula ve Hesap Oluştur',
    verifyingCode: 'Doğrulanıyor…',
    smsSent: '6 haneli kod gönderildi:',
    invalidOtp: 'Geçersiz kod. Tekrar deneyin.',
    accountCreated: 'Hesap oluşturuldu! Şimdi giriş yapabilirsiniz.',
    backToLanding: 'Ana sayfaya dön',
    forgotPassword: 'Şifremi unuttum?',
    forgotPasswordTitle: 'Şifrenizi sıfırlayın',
    forgotPasswordDesc: 'E-postanızı girin, size sıfırlama bağlantısı gönderelim.',
    sendResetLink: 'Sıfırlama bağlantısı gönder',
    sendingResetLink: 'Gönderiliyor…',
    resetEmailSent: 'Bağlantı gönderildi! Gelen kutunuzu kontrol edin.',
    income: 'Gelir',
    expenses: 'Gider',
    balance: 'Bakiye',
    addTransaction: 'İşlem Ekle',
    description: 'Açıklama',
    descriptionPlaceholder: 'Açıklama',
    amount: 'Tutar',
    amountPlaceholder: 'Tutar',
    incomeOption: 'Gelir',
    expenseOption: 'Gider',
    type: 'Tür',
    addBtn: 'Ekle',
    transactions: 'İşlemler',
    allTypes: 'Tüm Türler',
    allCategories: 'Tüm Kategoriler',
    date: 'Tarih',
    category: 'Kategori',
    noTransactions: 'İşlem bulunamadı',
    searchPlaceholder: 'Açıklama ara…',
    dateFrom: 'Başlangıç',
    dateTo: 'Bitiş',
    clearFilters: 'Temizle',
    sortBy: 'Sırala',
    sortDateDesc: 'En yeni önce',
    sortDateAsc: 'En eski önce',
    sortAmountDesc: 'Tutar: yüksek → düşük',
    sortAmountAsc: 'Tutar: düşük → yüksek',
    deleteTransaction: 'İşlemi Sil',
    deleteConfirmLine1: 'Silmek istediğinize emin misiniz?',
    cancelBtn: 'İptal',
    deleteBtn: 'Sil',
    food: 'Yiyecek',
    housing: 'Konut',
    utilities: 'Faturalar',
    transport: 'Ulaşım',
    entertainment: 'Eğlence',
    salary: 'Maaş',
    freelance: 'Serbest Çalışma',
    investment: 'Yatırım',
    rental: 'Kira Geliri',
    bonus: 'Bonus',
    other: 'Diğer',
    dailyDist: 'Günlük Bakiye',
    dailyDistDay: 'Gün',
    expenseBreakdown: 'Gider Dağılımı',
    recentActivity: 'Son İşlemler',
    noTransactionsDash: 'Henüz işlem yok',
    addFirstTransaction: 'İlk gelirinizi veya giderinizi ekleyin.',
    statAvgDaily: 'Günlük Ort. Harcama',
    statDaysElapsed: 'gün geçti',
    statDaysLeft: 'Kalan Gün',
    statOfMonth: '/',
    statTopCat: 'En Çok Kategori',
    statLargestExp: 'En Büyük Gider',
    statSavingsRate: 'Birikim Oranı',
    statAllTime: 'Tüm zamanlar',
    statVsLastMonth: 'Geçen aya göre',
    statSpending: 'harcama',
    statThisMonth: 'Bu Ay',
    statTransactions: 'işlem',
    statTransaction: 'işlem',
    statTxCount: 'işlem',
    dailyDistTapHint: 'Detaylar için bir çubuğa dokunun',
    dailyDistEmpty: 'O gün için işlem yok',
    dailyDistNet: 'Net',
    projTitle: 'Ay sonu tahmini',
    projSubtitle: 'tipik günlük harcama + bilinen ödemeler baz alınarak',
    projSpentSoFar: 'harcandı',
    projDaysLeft: 'gün kaldı',
    projVsLast: 'geçen aya göre',
    projScheduled: 'planlanmış',
    runningBalance: 'Bakiye',
    totalBudget: 'Toplam Bütçe',
    totalGoals: 'Toplam Hedef',
    totalSaved: 'Toplam Birikim',
    goalsSummary: 'Birikim Hedefleri',
    noTransactionsAnalytics: 'Analiz için işlem ekleyin',
    avgExpense: 'Ort. Gider',
    busiestDay: 'En Yoğun Gün',
    biggestExpense: 'En Büyük Gider',
    last30Days: 'Son 30 Gün',
    byCategory: 'Kategoriye Göre',
    spendingTrends: 'Harcama Trendi',
    thisMonth: 'Bu Ay',
    lastMonth: 'Geçen Ay',
    vsLastMonth: 'geçen aya göre',
    topMovers: 'Kategori Değişimleri',
    catAddNew: 'Yeni kategori',
    catAddPlaceholder: 'Kategori adı…',
    catAddErr_empty: 'Bir isim girin.',
    catAddErr_reserved: 'Bu isim rezerve edilmiş.',
    catAddErr_exists: 'Bu kategori zaten var.',
    budgets: 'Bütçeler',
    budgetEmpty: 'Henüz bütçe yok. Aylık limitler belirleyin.',
    budgetAdd: 'Bütçe Ekle',
    budgetEdit: 'Bütçeyi Düzenle',
    budgetMonthlyLimit: 'Aylık Limit',
    budgetSpent: 'Harcanan',
    budgetRemaining: 'Kalan',
    budgetOverBy: 'Aşım:',
    budgetOnTrack: 'Yolunda',
    budgetWarning: 'Limite yakın',
    budgetExceeded: 'Bütçe aşıldı',
    budgetSelectCategory: 'Kategori',
    toastTxAdded: 'İşlem eklendi',
    toastTxDeleted: 'İşlem silindi',
    toastTxUpdated: 'İşlem güncellendi',
    toastGoalSaved: 'Hedef kaydedildi',
    toastGoalDeleted: 'Hedef silindi',
    toastBudgetSaved: 'Bütçe kaydedildi',
    toastBudgetDeleted: 'Bütçe kaldırıldı',
    toastSubAdded: 'Abonelik eklendi',
    toastSubUpdated: 'Abonelik güncellendi',
    toastSubDeleted: 'Abonelik silindi',
    permissionDenied: 'İzin reddedildi',
    subAllCategories: 'Tüm Kategoriler',
    subFilterByCat: 'Kategoriye göre filtrele',
    subscriptions: 'Abonelikler',
    subMonthlyTotal: 'Aylık Toplam',
    subActive: 'aktif',
    subEmpty: 'Henüz abonelik yok. Eklemek için + tuşuna basın.',
    subAdd: 'Abonelik Ekle',
    subEdit: 'Düzenle',
    subName: 'Hizmet Adı',
    subBillingCycle: 'Fatura Dönemi',
    subStartedAt: 'Başlangıç',
    subNextBilling: 'Sonraki Fatura',
    subNotes: 'Notlar',
    subNotesPlaceholder: 'İsteğe bağlı notlar',
    subToday: 'Bugün',
    subOverdue: 'Gecikmiş',
    subDays: 'gün',
    subMonthsActive: 'Aktif Ay',
    subWeeksActive: 'Aktif Hafta',
    subYearsActive: 'Aktif Yıl',
    subTotalSpent: 'Toplam Harcama',
    subAutoCharge: 'Otomatik gider olarak kaydet',
    subAutoChargeDesc: 'Açıksa her fatura tarihi otomatik gider olarak kaydedilir.',
    subAutoChargeBadge: 'Oto',
    subDeleteTitle: 'Aboneliği Sil',
    subCycle_weekly: 'Haftalık',
    subCycle_monthly: 'Aylık',
    subCycle_yearly: 'Yıllık',
    subCat_ai: 'Yapay Zeka',
    subCat_entertainment: 'Eğlence',
    subCat_music: 'Müzik',
    subCat_finance: 'Finans',
    subCat_productivity: 'Verimlilik',
    subCat_health: 'Sağlık',
    subCat_news: 'Haber',
    subCat_telecom: 'Telekom',
    subCat_other: 'Diğer',
    dashGoals: 'Birikim Hedefleri',
    dashGoalsSeeAll: 'Tümü',
    goalAdd: 'Hedef Ekle',
    goalEdit: 'Hedefi Düzenle',
    goalEmoji: 'İkon',
    goalName: 'Hedef Adı',
    goalNamePlaceholder: 'Tatil, laptop, acil fon…',
    goalTarget: 'Hedef',
    goalSaved: 'Biriktirilen',
    goalTargetDate: 'Hedef tarihi',
    goalOptional: 'isteğe bağlı',
    goalEmpty: 'Henüz hedef yok. Eklemek için + tuşuna basın.',
    goalDeleteTitle: 'Hedefi Sil',
    goalComplete: 'Hedefe ulaşıldı!',
    goalRemaining: 'kaldı',
    goalDaysLeft: 'gün kaldı',
    goalToday: 'Bugün bitiyor',
    goalOverdue: 'Geçti',
    subReminder: 'E-posta Hatırlatıcı',
    subReminderNone: 'Hatırlatıcı yok',
    subReminder3: '3 gün önce',
    subReminder7: '7 gün önce',
    subReminder14: '14 gün önce',
    profileTitle: 'Profil',
    displayName: 'Görünen Ad',
    displayNamePlaceholder: 'Adınız',
    currencyLabel: 'Para Birimi',
    saveBtn: 'Kaydet',
    savingBtn: 'Kaydediliyor…',
    linkedAccounts: 'Bağlı Hesaplar',
    linkedEmail: 'E-posta',
    linkedPhone: 'Telefon',
    notLinked: 'Bağlı değil',
    landingTagline: 'Ücretsiz · Kredi kartı gerekmez',
    landingHeadline1: 'Birikimini',
    landingHeadline2: 'büyüt.',
    landingSubtitle: 'Gelir ve gider ekleyin, abonelikleri takip edin, banka ekstrelerinizi yapay zekâyla içe aktarın. Birikimini birik birik büyüt.',
    landingGetStarted: 'Ücretsiz hesap oluştur',
    landingSignIn: 'Giriş yap',
    landingFeature1Title: 'Saniyeler içinde işlem ekleyin',
    landingFeature1Desc: 'Açıklama yazın, tutarı girin, kategori seçin. Hepsi bu. Kurulum yok, form yok, zorluk yok.',
    landingFeature2Title: 'Harcamalarınıza tek bakışta hakim olun',
    landingFeature2Desc: 'Kontrol paneliniz uygulamayı açar açmaz bakiyenizi, son işlemleri ve 30 günlük dökümü gösterir.',
    landingFeature3Title: 'Kendi para biriminizde çalışır',
    landingFeature3Desc: 'USD, EUR, GBP, TRY, JPY ve daha fazlası arasından seçin. Tercihleriniz her ekranda senkronize olur.',
    landingFeature4Title: 'Dosya yükle — yapay zeka okusun',
    landingFeature4Desc: 'Banka ekstresi PDF\'i veya fotoğraf yükleyin. Yapay zeka tüm işlemleri otomatik çıkarır, siz hiçbir şey yazmak zorunda kalmazsınız.',
    landingFeature5Title: 'Aboneliklerinizi kaçırmayın',
    landingFeature5Desc: 'Tüm tekrar eden hizmetlerinizi tek yerde takip edin. Fatura öncesinde e-posta hatırlatıcısı alın, sürprizler yaşamayın.',
    landingFeature6Title: 'Tasarruf hedefleri belirleyin',
    landingFeature6Desc: 'Tatil, laptop, acil fon — her şey için hedef oluşturun. Birikim yaptıkça ilerleme çubuğunun dolduğunu izleyin.',
    landingCtaTitle: 'Bugün takibe başlayın.',
    landingCtaSub: 'Sonsuza kadar ücretsiz · Kredi kartı gerekmez',
    editBtn: 'Düzenle',
    preferencesTitle: 'Tercihler',
    darkMode: 'Karanlık Mod',
    lightMode: 'Aydınlık Mod',
    themeSystem: 'Sistem',
    langSystem: 'Sistem',
    language: 'Dil',
    theme: 'Tema',
    showAdvanced: 'Gelişmiş',
    hideAdvanced: 'Gelişmişi gizle',
    toastProfileSaved: 'Profil kaydedildi',
    biometricLock: 'Yüz Tanıma / Parmak İzi Kilidi',
    bioUnlockBtn: 'Yüz Tanıma / Parmak İzi ile Aç',
    bioUsePassword: 'Şifre ile giriş yap',
    offlineMode: 'İnternet bağlantısı yok',
    offlinePending: 'bekliyor',
    offlineSyncing: 'Senkronize ediliyor',
    recTitle: 'Tekrarlayan',
    recEmpty: 'Henüz tekrarlayan kural yok. Eklemek için + tuşuna basın.',
    recAdd: 'Kural Ekle',
    recEdit: 'Kuralı Düzenle',
    recSaved: 'Kural kaydedildi',
    recDeleted: 'Kural silindi',
    recFrequency: 'Sıklık',
    rec_weekly: 'Haftalık',
    rec_monthly: 'Aylık',
    rec_yearly: 'Yıllık',
    recDayOfMonth: 'Ayın Günü',
    recStartDate: 'Başlangıç Tarihi',
    recEndDate: 'Bitiş Tarihi',
    recDeleteTitle: 'Kuralı Sil',
    recPaused: 'Duraklatıldı',
    recActive: 'Aktif',
    recNextRun: 'Sonraki',
    navRecurring: 'Tekrarlayan',
    subStatusActive: 'Aktif',
    subStatusInactive: 'Pasif',
    subAddAsExpense: 'Gider Olarak Ekle',
    subExpenseAdded: 'Eklendi!',
    importTitle: 'Hesap Özeti İçe Aktar',
    importDesc: 'Banka veya kredi kartı hesap özeti fotoğrafı çekin ya da PDF yükleyin. Yapay zeka işlemleri otomatik çıkarır.',
    importAnalyzing: 'Hesap özeti analiz ediliyor…',
    importCamera: 'Fotoğraf Çek',
    importCameraDesc: 'Banka ekstrenizi fotoğraflayın',
    importGallery: 'Galeriden Seç',
    importGalleryDesc: 'Mevcut bir görüntü seçin',
    importPDF: 'PDF Yükle',
    importPDFDesc: 'PDF banka ekstresi seçin',
    importPreviewCount: 'işlem bulundu. İçe aktarmadan önce kategorileri düzenleyin.',
    importConfirm: 'İçe Aktar',
    importSuccess: 'işlem içe aktarıldı',
    importNoTxFound: 'İşlem bulunamadı. Dosyanın net bir banka ekstresi olduğundan emin olun.',
    monthlyOverview: 'Aylık Özet',
    insightHowGoing: 'Bu ay nasıl gidiyorum?',
    insightSameDayLastMonth: 'geçen ay aynı günde',
    insightOnTrack: 'Geçen ayın altında',
    insightOverSpending: 'Geçen ayı aştı',
    dashCustomize: 'Kontrol Panelini Düzenle',
    dashSectionStats: 'İstatistik Kartları',
    dashSectionBreakdown: 'Gider Dağılımı',
    dashSectionDaily: 'Günlük Bakiye',
    dashSectionProjection: 'Ay Tahmini',
    dashSectionRecent: 'Son İşlemler',
    dashSectionGoals: 'Birikim Hedefleri',
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [langMode, setLangModeState] = useState('system');
  const [systemLang] = useState(detectSystemLang);
  const [langChecked, setLangChecked] = useState(false);

  const lang = langMode === 'system' ? systemLang : langMode;

  useEffect(() => {
    AsyncStorage.getItem('lang').then(v => {
      if (v === 'en' || v === 'tr' || v === 'system') setLangModeState(v);
    }).finally(() => setLangChecked(true));
  }, []);

  const setLangMode = (mode) => {
    setLangModeState(mode);
    if (mode === 'system') AsyncStorage.removeItem('lang');
    else AsyncStorage.setItem('lang', mode);
  };

  const t = (key, params) => {
    const val = translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
    if (typeof val === 'function') return val(params);
    return val;
  };

  const formatDate = (dateStr) => {
    if (!dateStr) return '';
    const [y, m, d] = String(dateStr).split('T')[0].split('-').map(Number);
    if (!y || !m || !d) return dateStr;
    const date = new Date(y, m - 1, d);
    return date.toLocaleDateString(lang === 'tr' ? 'tr-TR' : 'en-US', {
      day: 'numeric', month: 'short', year: 'numeric',
    });
  };

  const toggleLang = () => {
    const next = langMode === 'system' ? 'en' : langMode === 'en' ? 'tr' : 'system';
    setLangMode(next);
  };

  return (
    <LangContext.Provider value={{ t, lang, toggleLang, formatDate, langMode, setLangMode, langChecked }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
